/* eslint-disable no-unused-vars */
export enum Preference {
  CONFETTI_ON_SESSION_COMPLETION = 'CONFETTI_ON_SESSION_COMPLETION',
  SHOW_ELAPSED_SECONDS_IN_ACTIVE_SESSION = 'SHOW_ELAPSED_SECONDS_IN_ACTIVE_SESSION',
}
